# Generated by Django 3.2.15 on 2022-09-17 02:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=cloudinary.models.CloudinaryField(default='https://asset.cloudinary.com/markhewitt76/c1ad8ca7b6567a75684439f66c0b2dd5', max_length=255, verbose_name='image'),
        ),
    ]
