# Generated by Django 3.2.15 on 2022-09-21 13:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_alter_category_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=cloudinary.models.CloudinaryField(default='cpic_placeholder', max_length=255, verbose_name='image'),
        ),
    ]
