# Generated by Django 3.2.15 on 2022-09-21 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_alter_category_category_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
    ]
